### PR TITLE
Support loading views from alternate bundles

### PR DESCRIPTION
**Pull request by aceontech**
I added an additional view initializer to `LMViewBuilder` which takes in an optional `NSBundle`. This change allows views to be loaded from external bundles, e.g. from a `.framework`. Verified in production project.

Example usage:
```swift
let bundle = Bundle(for: HMNavigationBar.self)
let v = LMViewBuilder.view(withName: "HMNavigationBar", bundle: bundle, owner: self, root: nil)
```

### CODE REVIEW

**Comment by gk-brown** [comment]
While I understand the theoretical motivation behind this change, I'd like to better understand the practical aspect of it. Specifically, what problem are you attempting to solve by storing markup documents in a separate bundle?

The reason I ask is because the main bundle isn't only used for loading markup - it's also used to load property templates, localized strings, font and color tables, and images. Allowing the caller to customize the location of the markup document implies that the location of these other resources should also be customizable. They could potentially all be loaded from the same bundle passed to `viewWithName:bundle:owner:root:`, but this would represent a much deeper change. 

It also presents some design challenges. Property templates and font/color tables are currently cached in static dictionaries that are effectively associated with the main bundle. Should all resources from all bundles be cached in a single dictionary, or should there be one cache per bundle?

These questions are the main reason I haven't attempted to add support for custom bundles. However, if you could provide a little more detail on what you are trying to accomplish, maybe we can come up with an alternate solution?

**Comment by aceontech** [comment]
The project I'm working on is split into various internal frameworks, one of which being a UI framework. It hosts the reusable UI components. From this point of view, I think it's valid to (optionally) allow the caller to define the `NSBundle`, but you're right, it requires a much deeper change.

I think you should be able to cache resources per bundle. But a fallback to `NSBundle.mainBundle` is probably also required for certain types of resources which often reside in the main bundle (e.g. fonts).

**Comment by gk-brown** [comment]
I see. I think it may be possible to handle this without any API changes. The `bundleForClass:` method of `NSBundle` could potentially be used to identify the bundle of the view's owner. This bundle could then be used in place of the main bundle in `viewWithName:owner:root:` as well as in any instance methods (e.g. when loading images and localized string values). Static resources (i.e. property templates and font/color tables) would still be loaded from the main bundle. Would this work for you?

**Comment by gk-brown** [comment]
Correction - images would still need to be loaded from the main bundle, since they are loaded by code that does not have access to the document owner. Localized strings could be loaded from the owner's bundle, though.

**Comment by gk-brown** [comment]
I just pushed this change to the development branch. Take a look and let me know what you think.

**Comment by aceontech** [comment]
> The bundleForClass: method of NSBundle could potentially be used to identify the bundle of the view's owner.

Smart! I was using `bundleForClass` to determine the bundle manually, but indeed, it may be much better to do so transparently where possible. 

> Static resources (i.e. property templates and font/color tables) would still be loaded from the main bundle. Would this work for you?

At first glance, it makes complete sense to continue to load static content like fonts, images, etc. from the main bundle as this is usually where they reside anyway. So yes, I think so.

> Localized strings could be loaded from the owner's bundle, though.

Although in theory you could spread your localization files across frameworks, I'm not sure people actually do so? I think most aggregate localization into the actual app, thus the main bundle.

I'll include the development branch in my project and play around with it.

**Comment by gk-brown** [comment]
> Although in theory you could spread your localization files across frameworks, I'm not sure people actually do so? I think most aggregate localization into the actual app, thus the main bundle.

You're probably right. I'll revert that part of the change - we can always revisit later, if necessary.

**Comment by aceontech** [comment]
Okay, so I managed to build the framework from the `development` branch, though I had to remove the tvOS build scheme from the `xcworkspace` in order to get the build to work. Was getting the following error:

```
*** Building scheme "MarkupKit" in MarkupKit.xcworkspace
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:iOS Simulator, id:3EA3B075-DE4D-44CF-AD6E-5BE06C660918 }

	Available destinations for the "MarkupKit" scheme:
		{ platform:tvOS Simulator, id:6D7966B6-CDA9-44EA-A680-A66AA56707FA, OS:10.1, name:Apple TV 1080p }

	Ineligible destinations for the "MarkupKit" scheme:
		{ platform:tvOS, id:dvtdevice-DVTiOSDevicePlaceholder-appletvos:placeholder, name:Generic tvOS Device }
		{ platform:tvOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-appletvsimulator:placeholder, name:Generic tvOS Simulator Device }
A shell task (/usr/bin/xcrun xcodebuild -workspace <<omitted>>/Carthage/Checkouts/MarkupKit/MarkupKit.xcworkspace -scheme MarkupKit -configuration Release -sdk iphonesimulator -destination "platform=iOS Simulator,id=3EA3B075-DE4D-44CF-AD6E-5BE06C660918" -destination-timeout 3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 70:
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:iOS Simulator, id:3EA3B075-DE4D-44CF-AD6E-5BE06C660918 }

	Available destinations for the "MarkupKit" scheme:
		{ platform:tvOS Simulator, id:6D7966B6-CDA9-44EA-A680-A66AA56707FA, OS:10.1, name:Apple TV 1080p }

	Ineligible destinations for the "MarkupKit" scheme:
		{ platform:tvOS, id:dvtdevice-DVTiOSDevicePlaceholder-appletvos:placeholder, name:Generic tvOS Device }
		{ platform:tvOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-appletvsimulator:placeholder, name:Generic tvOS Simulator Device }

```

This may have something to do with my setup, but the `master` branch doesn't have this issue. Traced it back to [this issue](https://github.com/Carthage/Carthage/issues/950) in the Carthage project, but it's still not clear to me what is actually going on.

In any case, I'll continue testing and let you know if I run into trouble.

**Comment by aceontech** [comment]
Quick follow-up:

[This fix in colemancda/aerogear-ios-http](https://github.com/colemancda/aerogear-ios-http/commit/10b0655109d5d024f922c1b66653b9a54f166877) talks about needing to set the `TARGETED_DEVICE_FAMILY` in case of tvOS or watchOS projects. Related thread: https://github.com/Carthage/Carthage/issues/950#issuecomment-176291457.

**Comment by gk-brown** [comment]
Could it be a Carthage problem? I'm able to build the development branch on two different machines.

What version of Xcode are you running? Can you try running the _package.sh_ script in the project root directory and see if that works?

**Comment by aceontech** [comment]
Yeah could be. I've been able to build it with Carthage successfully a couple of times today, without modification.. So it only happens *sometimes* :-\

I was able to run `package.sh` without issues, so it's probably nothing to worry about.

**Comment by gk-brown** [comment]
OK, great. Have you been able to test the updates with your project? If so, how did it go?

**Comment by gk-brown** [comment]
Great, thanks. Let me know if you run into any problems. If not, I'll probably package it up for release in the next day or so.

Out of curiosity, are you using Carthage to build MarkupKit for your project or are you using the compiled framework?

**Comment by aceontech** [comment]
Will do!

I'm using Carthage.It allows me to define which version or branch to check out and it builds the resulting `.framework`. This works reasonably well, 90% of the time ;-). 

Sometimes I wonder whether it's actually more trouble than it's worth. But then, Cocoapods or submodules are much worse, so I'll continue using it for the time being, I guess.

**Comment by gk-brown** [comment]
OK, good to know. I don't personally use either one myself, but I do publish MarkupKit via CocoaPods since I know a lot of other developers do use it. I've never done anything to explicitly enable Carthage support - do you think it is worth considering? Any idea what would be involved?

Alternatively, I could start preserving the release history so developers would have access to earlier compiled versions. I generally delete historical releases once I publish a new version, but I don't really have to do that...

**Comment by aceontech** [comment]
I always use MarkupKit through Carthage, so the support is there. All
Carthage really needs is a shared build scheme in Xcode, and properly
tagged releases in Git. Check and check 😉. The promise of Carthage is that
it's simpler and more hands off than Cocoapods, but it has its own issues
(mostly slowness at this point).

However, I've only used the iOS releases through Carthage, so perhaps it's
worth explicitly testing the tvOS release too at some point.

On Wed, 4 Jan 2017 at 15:34 Greg Brown <notifications@github.com> wrote:

OK, good to know. I don't personally use either one myself, but I do
publish MarkupKit via CocoaPods since I know a lot of other developers do
use it. I've never done anything to explicitly enable Carthage support - do
you think it is worth considering? Any idea what would be involved?


Alternatively, I could start preserving the release history so developers
would have access to earlier compiled versions. I generally delete
historical releases once I publish a new version, but I don't really have
to do that...




—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/gk-brown/MarkupKit/pull/76#issuecomment-270384222>, or mute
the thread

**Comment by aceontech** [comment]
One more note on Carthage: it can skip the build process if you attach the prebuilt frameworks to the GitHub release. Carthage will then simply download the binaries and unzip them in the right place instead of building everything from source. This is discussed in detail [here](https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file).

**Comment by gk-brown** [comment]
OK, thanks for the info. I'll take a look at the link.

**Comment by gk-brown** [comment]
Created https://github.com/gk-brown/MarkupKit/issues/77 to track this request.

**Pull request closed without merging**
